fullname: Linear Temporal Type Theory
shortname: lttt
organization: aerabi
community: false
synopsis: An implementation of linear temporal types
description: >
    An implementation of linear temporal types
authors:
  - name: Mohammad-Ali A'RÂBI
    initial: false
    email: aerabi@gmx.de
maintainers:
  - name: Mohammad-Ali A'RÂBI
    nickname: aerabi
license:
  fullname: MIT license
  identifier: MIT
namespace: LTTT
publications:
  - pub_title: The Essence of Event-Driven Programming
    pub_url: https://128.232.0.20/~nk480/essence-of-events.pdf
  - pub_title: Linear Temporal Type Theory for Event-based Reactive Programming
    pub_url: https://www.semanticscholar.org/paper/Linear-Temporal-Type-Theory-for-Event-based-Paykin-Krishnaswami/4b8eccab1340c9d1035728ba5b198eab41ab66f3
keywords:
  - name: linear types
  - name: temporal type theory
  - name: typing
  - name: type theory
categories:
  - name: Mathematics/Logic/Type theory
action: true
supported_coq_versions:
  - text: Coq 8.4 or higher
    opam: '{(>= "8.7" & < "8.13~") | (= "dev")}'
tested_coq_opam_versions:
  - version: "8.4"
  - version: "8.5"
  - version: "8.6"
  - version: "8.7"
  - version: "8.8"
  - version: "8.9"
  - version: "8.10"
  - version: "8.11"
  - version: "8.12"
  - version: "dev"
dependencies:
  - opam:
      name: coq-generic-environments
    description: "[Coq Generic Environments](https://github.com/coq-community/generic-environments) which is used for typing and semantics"

