fullname: Linear Temporal Type Theory
shortname: lttt
namespace: LTTT
organization: aerabi
community: false
synopsis: An implementation of Linear-Time Temporal Type Theory
action: true
doi: 10.5281/zenodo.4749276
description: >
  An implementation of Linear-Time Temporal Type Theory

authors:
  - name: Mohammad-Ali A'RÂBI
    initial: false
    email: aerabi@gmx.de

maintainers:
  - name: Mohammad-Ali A'RÂBI
    nickname: aerabi

license:
  fullname: MIT license
  identifier: MIT

publications:
  - pub_title: The Essence of Event-Driven Programming
    pub_url: https://128.232.0.20/~nk480/essence-of-events.pdf
  - pub_title: Linear Temporal Type Theory for Event-based Reactive Programming
    pub_url: https://www.semanticscholar.org/paper/Linear-Temporal-Type-Theory-for-Event-based-Paykin-Krishnaswami/4b8eccab1340c9d1035728ba5b198eab41ab66f3

keywords:
  - name: linear types
  - name: temporal type theory
  - name: typing
  - name: type theory

categories:
  - name: Mathematics/Logic/Type theory

supported_coq_versions:
  - text: Coq 8.7 to 8.11
    opam: '{(>= "8.7" & < "8.12~")}'

tested_coq_opam_versions:
  - version: "8.7"
  - version: "8.8"
  - version: "8.9"
  - version: "8.10"
  - version: "8.11"

dependencies:
  - opam:
      name: 'coq-quickchick'
    description: Quickchick
